version: '3.7'
services:
  nginx:
    image: nginx:1.17.6-alpine
    ports:
      - "${LISTENIP:-127.0.0.1}:8080:80"
    volumes:
      - type: bind
        source: ./static
        target: /site/pianistica/static
      - type: bind
        source: ./serverless
        target: /site/pianistica/serverless
      - type: bind
        source: ./mime.types
        target: /site/pianistica/mime.types
      - type: bind
        source: ./serverless/nginx-dev.conf
        target: /site/pianistica/nginx.conf
    entrypoint:
      - nginx
      - '-c'
      - /site/pianistica/nginx.conf
